<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NotificationTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            [
                'event_code' => 'supplier.registered',
                'name' => 'Supplier Registered',
                'subject' => 'New Supplier Registration: {{supplier_name}}',
                'body_text' => 'A new supplier {{supplier_name}} ({{supplier_code}}) has registered and is awaiting review.',
                'whatsapp_body' => null,
                'body_html' => '<p>A new supplier <strong>{{supplier_name}}</strong> ({{supplier_code}}) has registered and is awaiting your review.</p>',
                'type' => 'info',
                'email_enabled' => true,
                'inapp_enabled' => true,
                'whatsapp_enabled' => false,
                'sms_enabled' => false,
                'allow_self_notify' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'event_code' => 'supplier.approved',
                'name' => 'Supplier Approved',
                'subject' => 'Your supplier account has been approved — Al Injaz',
                'body_text' => 'Congratulations! Your supplier account {{supplier_name}} has been approved. Please set your password using this link: {{set_password_url}}',
                'whatsapp_body' => 'Congratulations! Your supplier account {{supplier_name}} has been approved. Set your password: {{set_password_url}}',
                'body_html' => '<p>Congratulations! Your supplier account <strong>{{supplier_name}}</strong> has been approved.</p><p>Please set your password using the button below.</p>',
                'type' => 'success',
                'email_enabled' => true,
                'inapp_enabled' => false,
                'whatsapp_enabled' => true,
                'sms_enabled' => false,
                'allow_self_notify' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'event_code' => 'supplier.rejected',
                'name' => 'Supplier Rejected',
                'subject' => 'Your supplier application was not approved — Al Injaz',
                'body_text' => 'We regret to inform you that your supplier application for {{supplier_name}} has not been approved. Reason: {{rejection_reason}}',
                'whatsapp_body' => 'We regret to inform you that your supplier application for {{supplier_name}} has not been approved. Reason: {{rejection_reason}}',
                'body_html' => '<p>We regret to inform you that your supplier application for <strong>{{supplier_name}}</strong> has not been approved.</p><p><strong>Reason:</strong> {{rejection_reason}}</p>',
                'type' => 'danger',
                'email_enabled' => true,
                'inapp_enabled' => false,
                'whatsapp_enabled' => true,
                'sms_enabled' => false,
                'allow_self_notify' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'event_code' => 'supplier.more_info_requested',
                'name' => 'More Information Required',
                'subject' => 'Additional information required for your supplier application',
                'body_text' => 'We require additional information to process your supplier application. Notes: {{more_info_notes}}',
                'whatsapp_body' => 'We require additional information to process your supplier application. Notes: {{more_info_notes}}',
                'body_html' => '<p>We require additional information to process your supplier application.</p><p><strong>Notes:</strong> {{more_info_notes}}</p>',
                'type' => 'warning',
                'email_enabled' => true,
                'inapp_enabled' => false,
                'whatsapp_enabled' => true,
                'sms_enabled' => false,
                'allow_self_notify' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'event_code' => 'task.assigned',
                'name' => 'Task Assigned',
                'subject' => 'Task assigned to you: {{task_title}}',
                'body_text' => 'You have been assigned a new task: {{task_title}} in project {{project_name}} by {{assigned_by}}.',
                'whatsapp_body' => 'You have been assigned a new task: {{task_title}} in project {{project_name}} by {{assigned_by}}.',
                'body_html' => '<p>You have been assigned a new task: <strong>{{task_title}}</strong> in project <strong>{{project_name}}</strong> by {{assigned_by}}.</p>',
                'type' => 'info',
                'email_enabled' => false,
                'inapp_enabled' => true,
                'whatsapp_enabled' => true,
                'sms_enabled' => false,
                'allow_self_notify' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'event_code' => 'project.created',
                'name' => 'Project Created',
                'subject' => 'New project: {{project_name}}',
                'body_text' => 'A new project {{project_name}} has been created by {{created_by}}.',
                'whatsapp_body' => null,
                'body_html' => '<p>A new project <strong>{{project_name}}</strong> has been created by {{created_by}}.</p>',
                'type' => 'info',
                'email_enabled' => false,
                'inapp_enabled' => true,
                'whatsapp_enabled' => false,
                'sms_enabled' => false,
                'allow_self_notify' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'event_code' => 'user.created',
                'name' => 'Welcome — Set Your Password',
                'subject' => 'Welcome to Al Injaz — Please set your password',
                'body_text' => 'Your account has been created. Please set your password using this link: {{set_password_url}}',
                'whatsapp_body' => null,
                'body_html' => '<p>Your account has been created.</p><p>Please set your password using the button below.</p>',
                'type' => 'info',
                'email_enabled' => true,
                'inapp_enabled' => false,
                'whatsapp_enabled' => false,
                'sms_enabled' => false,
                'allow_self_notify' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'event_code' => 'task.reminder',
                'name' => 'Task reminder',
                'subject' => 'Reminder: {{task_title}}',
                'body_text' => 'Reminder for task "{{task_title}}". Note: {{reminder_note}} Due: {{due_at}}',
                'whatsapp_body' => 'Reminder: {{task_title}}. {{reminder_note}} Due: {{due_at}}',
                'body_html' => '<p>Reminder for task <strong>{{task_title}}</strong>.</p><p>{{reminder_note}}</p><p>Due: {{due_at}}</p>',
                'type' => 'info',
                'email_enabled' => true,
                'inapp_enabled' => true,
                'whatsapp_enabled' => false,
                'sms_enabled' => false,
                'allow_self_notify' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'event_code' => 'task.system_reminder',
                'name' => 'Task system reminder',
                'subject' => 'Scheduled reminder: {{task_title}}',
                'body_text' => 'Your task "{{task_title}}" has a scheduled reminder. Due: {{due_at}}',
                'whatsapp_body' => 'Scheduled reminder: {{task_title}}. Due: {{due_at}}',
                'body_html' => '<p>Scheduled reminder for <strong>{{task_title}}</strong>.</p><p>Due: {{due_at}}</p>',
                'type' => 'info',
                'email_enabled' => true,
                'inapp_enabled' => true,
                'whatsapp_enabled' => false,
                'sms_enabled' => false,
                'allow_self_notify' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'event_code' => 'task.comment_reminder',
                'name' => 'Comment follow-up',
                'subject' => 'Comment reminder: {{task_title}}',
                'body_text' => 'Follow-up on your comment on "{{task_title}}": {{comment_preview}}',
                'whatsapp_body' => 'Comment reminder on {{task_title}}: {{comment_preview}}',
                'body_html' => '<p>Follow-up on your comment on <strong>{{task_title}}</strong>:</p><p>{{comment_preview}}</p>',
                'type' => 'info',
                'email_enabled' => true,
                'inapp_enabled' => true,
                'whatsapp_enabled' => false,
                'sms_enabled' => false,
                'allow_self_notify' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('notification_templates')->upsert(
            $templates,
            ['event_code'],
            ['name', 'subject', 'body_text', 'whatsapp_body', 'body_html', 'type', 'email_enabled', 'inapp_enabled', 'whatsapp_enabled', 'sms_enabled', 'allow_self_notify', 'updated_at']
        );
    }
}
